#pragma checksum "..\..\..\..\Controls\AutocompleteTextBox.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "217B0C4C922C77856777067AE62555541D6779CC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using StationApp.UI.Converters;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace StationApp.UI.Controls {
    
    
    /// <summary>
    /// AutocompleteTextBox
    /// </summary>
    public partial class AutocompleteTextBox : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 5 "..\..\..\..\Controls\AutocompleteTextBox.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal StationApp.UI.Controls.AutocompleteTextBox Root;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\Controls\AutocompleteTextBox.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InputTextBox;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\Controls\AutocompleteTextBox.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup SuggestionsPopup;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\Controls\AutocompleteTextBox.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox SuggestionsList;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.26.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/StationApp.UI;component/controls/autocompletetextbox.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Controls\AutocompleteTextBox.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.26.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Root = ((StationApp.UI.Controls.AutocompleteTextBox)(target));
            return;
            case 2:
            this.InputTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 53 "..\..\..\..\Controls\AutocompleteTextBox.xaml"
            this.InputTextBox.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.InputTextBox_OnPreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 54 "..\..\..\..\Controls\AutocompleteTextBox.xaml"
            this.InputTextBox.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.FocusableElement_OnLostKeyboardFocus);
            
            #line default
            #line hidden
            return;
            case 3:
            this.SuggestionsPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 4:
            this.SuggestionsList = ((System.Windows.Controls.ListBox)(target));
            
            #line 76 "..\..\..\..\Controls\AutocompleteTextBox.xaml"
            this.SuggestionsList.PreviewMouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.SuggestionsList_OnPreviewMouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 77 "..\..\..\..\Controls\AutocompleteTextBox.xaml"
            this.SuggestionsList.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.SuggestionsList_OnPreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 78 "..\..\..\..\Controls\AutocompleteTextBox.xaml"
            this.SuggestionsList.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.FocusableElement_OnLostKeyboardFocus);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

