<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>StationApp.BackupRestoreTool</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StationApp.Domain\StationApp.Domain.csproj" />
    <ProjectReference Include="..\StationApp.Infrastructure\StationApp.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
  </ItemGroup>
</Project>
